### ISSUE TITLE
fur Color field not working when geo-node appended from Asset Browser

### ISSUE THREAD

**Issue by SyRaza** [blackears/blenderFurNodes#1]
I'm running and testing out this setup on Blender 3.4.1.

Tested in clean new blender file and in the blend file provided on github

Steps:

1. Opened a new blender file.
2. Added folder folder containing unzipped files downloaded from github to Blender's file paths.
3. Added Suzanne
4. Roughly texture painted on suzanne
5. Baked Diffuse to image.
6. Duplicated Suzanne
7. Scaled the duplicated Suzanne to create the cage
8. Added Cube
9. Dropped Shader from Asset browser onto Cube
10. Added a new geometry node and the dropped Geometry node from Asset browser into the geometry node editor, connecting them as shown in youtube video.
11. Set Body Mesh to Suzanne
12. Set Body Cage to Suzanne.001
13. Set Cage UV Map to UVMap
14. Set Fur Color to baked diffuse
15. Set Material to furShader
16. Set Density to 4000
17. Set furColor, and furUV
18. Switch to Rendered view. The following is the result.

![image](https://user-images.githubusercontent.com/13445113/224811376-18fca8da-cdef-4e2d-9b3e-b3b5b5197f25.png)

Now, I opened the blend file provided here in github.

I did the same thing, expect, instead of creating a cube and dropping in the shader and geometery node, I simply duplicated the fur object you'd already created, but set it to my suzanne heads/fur color.

Again, here's the result.
![image](https://user-images.githubusercontent.com/13445113/224812005-ad9926ea-20dc-41bc-932d-585cd4f13358.png)

Not sure what the issue is.

**Comment by blackears** [comment]
You didn't mention setting up the output attributes.  Did you do this?

![image](https://user-images.githubusercontent.com/6724608/224863139-775c6a93-e2ea-4d39-8247-8482be5d15b9.png)

**Comment by SyRaza** [comment]
> 

I did. It's in the picture but I should have mentioned that in the steps too.

**Comment by blackears** [comment]
I went through the steps you listed and it worked for me.  Can you post a file with the model that isn't working?

**Comment by SyRaza** [comment]
As I was recreating the blend file to upload, I accidentally fixed my issue.

In the Output Attributes field, under 'furUv' I was entering furUV with a capital V. But blender is case sensitive and I didn't realise the nodes were setup with a lower case v since the common annotation is UV. I'm Glad I was able to figure it out though. Thanks!
